"""create calculations table

Revision ID: 0691cba37fcc
Revises: 
Create Date: 2026-09-18 16:55:09.873890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0691cba37fcc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calculations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_uuid', sa.String(length=36), nullable=False),
    sa.Column('history', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calculations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calculations_user_uuid'), ['user_uuid'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calculations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calculations_user_uuid'))

    op.drop_table('calculations')
    # ### end Alembic commands ###
